INFO 2024-11-27 07:21:29 _internal.py: 97]  * Restarting with watchdog (windowsapi)
DEBUG 2024-11-27 07:21:33 cmd.py: 1253] Popen(['git', 'version'], cwd=E:\Aiwi\Common\project3, stdin=None, shell=False, universal_newlines=False)
DEBUG 2024-11-27 07:21:33 cmd.py: 1253] Popen(['git', 'version'], cwd=E:\Aiwi\Common\project3, stdin=None, shell=False, universal_newlines=False)
DEBUG 2024-11-27 07:21:33 auth.py: 50] Trying paths: ['C:\\Users\\Hp\\.docker\\config.json', 'C:\\Users\\Hp\\.dockercfg']
DEBUG 2024-11-27 07:21:33 auth.py: 54] Found file at path: C:\Users\Hp\.docker\config.json
DEBUG 2024-11-27 07:21:33 auth.py: 242] Found 'credsStore' section
WARNING 2024-11-27 07:21:35 _internal.py: 97]  * Debugger is active!
INFO 2024-11-27 07:21:35 _internal.py: 97]  * Debugger PIN: 770-194-117
INFO 2024-11-27 07:21:35 FaceDetModelLoader.py: 16] Start to analyze the face detection model, model path: models, model category: face_detectionï¼Œmodel name: face_detection_1.0
INFO 2024-11-27 07:21:35 BaseModelLoader.py: 34] Successfully parsed the model configuration file meta.json!
INFO 2024-11-27 07:21:35 FaceDetModelLoader.py: 34] Successfully loaded the face detection model!
INFO 2024-11-27 07:21:35 FaceAlignModelLoader.py: 16] Start to analyze the face landmark model, model path: models, model category: face_alignmentï¼Œmodel name: face_alignment_1.0
INFO 2024-11-27 07:21:35 BaseModelLoader.py: 34] Successfully parsed the model configuration file meta.json!
INFO 2024-11-27 07:21:36 FaceAlignModelLoader.py: 29] Successfully loaded the face landmark model!
INFO 2024-11-27 07:21:38 _internal.py: 97] 127.0.0.1 - - [27/Nov/2024 07:21:38] "POST /upload_test HTTP/1.1" 200 -
INFO 2024-11-27 07:21:38 _internal.py: 97] 127.0.0.1 - - [27/Nov/2024 07:21:38] "[33mPOST /upload_file HTTP/1.1[0m" 404 -
INFO 2024-11-27 07:21:41 _internal.py: 97] 127.0.0.1 - - [27/Nov/2024 07:21:41] "POST /evaluate HTTP/1.1" 200 -
INFO 2024-11-27 07:21:41 _internal.py: 97] 127.0.0.1 - - [27/Nov/2024 07:21:41] "GET /static/6.jpg HTTP/1.1" 200 -
INFO 2024-11-27 07:21:42 _internal.py: 97] 127.0.0.1 - - [27/Nov/2024 07:21:42] "[35m[1mGET /get_all_files HTTP/1.1[0m" 500 -
INFO 2024-11-27 07:30:48 _internal.py: 97]  * Detected change in 'E:\\Aiwi\\Fake_News_Detection\\Flask_App(Modified)\\app5.py', reloading
INFO 2024-11-27 07:30:49 _internal.py: 97]  * Restarting with watchdog (windowsapi)
DEBUG 2024-11-27 07:30:54 cmd.py: 1253] Popen(['git', 'version'], cwd=E:\Aiwi\Common\project3, stdin=None, shell=False, universal_newlines=False)
DEBUG 2024-11-27 07:30:54 cmd.py: 1253] Popen(['git', 'version'], cwd=E:\Aiwi\Common\project3, stdin=None, shell=False, universal_newlines=False)
DEBUG 2024-11-27 07:30:54 auth.py: 50] Trying paths: ['C:\\Users\\Hp\\.docker\\config.json', 'C:\\Users\\Hp\\.dockercfg']
DEBUG 2024-11-27 07:30:54 auth.py: 54] Found file at path: C:\Users\Hp\.docker\config.json
DEBUG 2024-11-27 07:30:54 auth.py: 242] Found 'credsStore' section
WARNING 2024-11-27 07:30:57 _internal.py: 97]  * Debugger is active!
INFO 2024-11-27 07:30:57 _internal.py: 97]  * Debugger PIN: 770-194-117
INFO 2024-11-27 07:31:04 _internal.py: 97]  * Detected change in 'E:\\Aiwi\\Fake_News_Detection\\Flask_App(Modified)\\test.py', reloading
INFO 2024-11-27 07:31:07 _internal.py: 97]  * Restarting with watchdog (windowsapi)
DEBUG 2024-11-27 07:31:13 cmd.py: 1253] Popen(['git', 'version'], cwd=E:\Aiwi\Common\project3, stdin=None, shell=False, universal_newlines=False)
DEBUG 2024-11-27 07:31:13 cmd.py: 1253] Popen(['git', 'version'], cwd=E:\Aiwi\Common\project3, stdin=None, shell=False, universal_newlines=False)
DEBUG 2024-11-27 07:31:13 auth.py: 50] Trying paths: ['C:\\Users\\Hp\\.docker\\config.json', 'C:\\Users\\Hp\\.dockercfg']
DEBUG 2024-11-27 07:31:13 auth.py: 54] Found file at path: C:\Users\Hp\.docker\config.json
DEBUG 2024-11-27 07:31:13 auth.py: 242] Found 'credsStore' section
WARNING 2024-11-27 07:31:16 _internal.py: 97]  * Debugger is active!
INFO 2024-11-27 07:31:16 _internal.py: 97]  * Debugger PIN: 770-194-117
INFO 2024-11-27 07:31:19 _internal.py: 97]  * Detected change in 'E:\\Aiwi\\Fake_News_Detection\\Flask_App(Modified)\\app5.py', reloading
INFO 2024-11-27 07:31:19 _internal.py: 97]  * Detected change in 'E:\\Aiwi\\Fake_News_Detection\\Flask_App(Modified)\\app5.py', reloading
INFO 2024-11-27 07:31:20 _internal.py: 97]  * Restarting with watchdog (windowsapi)
DEBUG 2024-11-27 07:31:24 cmd.py: 1253] Popen(['git', 'version'], cwd=E:\Aiwi\Common\project3, stdin=None, shell=False, universal_newlines=False)
DEBUG 2024-11-27 07:31:24 cmd.py: 1253] Popen(['git', 'version'], cwd=E:\Aiwi\Common\project3, stdin=None, shell=False, universal_newlines=False)
DEBUG 2024-11-27 07:31:24 auth.py: 50] Trying paths: ['C:\\Users\\Hp\\.docker\\config.json', 'C:\\Users\\Hp\\.dockercfg']
DEBUG 2024-11-27 07:31:24 auth.py: 54] Found file at path: C:\Users\Hp\.docker\config.json
DEBUG 2024-11-27 07:31:24 auth.py: 242] Found 'credsStore' section
WARNING 2024-11-27 07:31:26 _internal.py: 97]  * Debugger is active!
INFO 2024-11-27 07:31:26 _internal.py: 97]  * Debugger PIN: 770-194-117
DEBUG 2024-11-29 03:50:03 cmd.py: 1253] Popen(['git', 'version'], cwd=E:\Aiwi\github upload\Fake_Face_detection, stdin=None, shell=False, universal_newlines=False)
DEBUG 2024-11-29 03:50:03 cmd.py: 1253] Popen(['git', 'version'], cwd=E:\Aiwi\github upload\Fake_Face_detection, stdin=None, shell=False, universal_newlines=False)
DEBUG 2024-11-29 03:50:03 auth.py: 50] Trying paths: ['C:\\Users\\Hp\\.docker\\config.json', 'C:\\Users\\Hp\\.dockercfg']
DEBUG 2024-11-29 03:50:03 auth.py: 54] Found file at path: C:\Users\Hp\.docker\config.json
DEBUG 2024-11-29 03:50:03 auth.py: 242] Found 'credsStore' section
INFO 2024-11-29 03:50:07 _internal.py: 97] [31m[1mWARNING: This is a development server. Do not use it in a production deployment. Use a production WSGI server instead.[0m
 * Running on http://127.0.0.1:3000
INFO 2024-11-29 03:50:07 _internal.py: 97] [33mPress CTRL+C to quit[0m
INFO 2024-11-29 03:50:07 _internal.py: 97]  * Restarting with watchdog (windowsapi)
DEBUG 2024-11-29 03:50:12 cmd.py: 1253] Popen(['git', 'version'], cwd=E:\Aiwi\github upload\Fake_Face_detection, stdin=None, shell=False, universal_newlines=False)
DEBUG 2024-11-29 03:50:12 cmd.py: 1253] Popen(['git', 'version'], cwd=E:\Aiwi\github upload\Fake_Face_detection, stdin=None, shell=False, universal_newlines=False)
DEBUG 2024-11-29 03:50:12 auth.py: 50] Trying paths: ['C:\\Users\\Hp\\.docker\\config.json', 'C:\\Users\\Hp\\.dockercfg']
DEBUG 2024-11-29 03:50:12 auth.py: 54] Found file at path: C:\Users\Hp\.docker\config.json
DEBUG 2024-11-29 03:50:12 auth.py: 242] Found 'credsStore' section
WARNING 2024-11-29 03:50:15 _internal.py: 97]  * Debugger is active!
INFO 2024-11-29 03:50:15 _internal.py: 97]  * Debugger PIN: 770-194-117
INFO 2024-11-29 03:50:20 _internal.py: 97] 127.0.0.1 - - [29/Nov/2024 03:50:20] "GET / HTTP/1.1" 200 -
INFO 2024-11-29 03:50:20 _internal.py: 97] 127.0.0.1 - - [29/Nov/2024 03:50:20] "[33mGET /favicon.ico HTTP/1.1[0m" 404 -
INFO 2024-11-29 03:51:57 FaceDetModelLoader.py: 16] Start to analyze the face detection model, model path: models, model category: face_detectionï¼Œmodel name: face_detection_1.0
INFO 2024-11-29 03:51:57 BaseModelLoader.py: 34] Successfully parsed the model configuration file meta.json!
INFO 2024-11-29 03:51:57 _internal.py: 97]  * Detected change in 'E:\\myenv\\Lib\\site-packages\\torchvision\\models\\_utils.py', reloading
INFO 2024-11-29 03:51:57 _internal.py: 97]  * Detected change in 'E:\\myenv\\Lib\\site-packages\\torch\\serialization.py', reloading
INFO 2024-11-29 03:51:57 _internal.py: 97]  * Detected change in 'E:\\myenv\\Lib\\site-packages\\torch\\nn\\modules\\container.py', reloading
INFO 2024-11-29 03:51:58 _internal.py: 97]  * Detected change in 'E:\\myenv\\Lib\\site-packages\\torch\\nn\\modules\\conv.py', reloading
INFO 2024-11-29 03:51:58 _internal.py: 97]  * Detected change in 'E:\\myenv\\Lib\\site-packages\\torch\\nn\\modules\\batchnorm.py', reloading
INFO 2024-11-29 03:51:58 _internal.py: 97]  * Detected change in 'E:\\myenv\\Lib\\site-packages\\torch\\nn\\modules\\activation.py', reloading
INFO 2024-11-29 03:51:58 FaceDetModelLoader.py: 34] Successfully loaded the face detection model!
INFO 2024-11-29 03:51:58 FaceAlignModelLoader.py: 16] Start to analyze the face landmark model, model path: models, model category: face_alignmentï¼Œmodel name: face_alignment_1.0
INFO 2024-11-29 03:51:58 BaseModelLoader.py: 34] Successfully parsed the model configuration file meta.json!
INFO 2024-11-29 03:51:58 _internal.py: 97]  * Detected change in 'E:\\myenv\\Lib\\site-packages\\torch\\nn\\modules\\pooling.py', reloading
INFO 2024-11-29 03:51:58 _internal.py: 97]  * Detected change in 'E:\\myenv\\Lib\\site-packages\\torch\\nn\\modules\\linear.py', reloading
INFO 2024-11-29 03:51:58 FaceAlignModelLoader.py: 29] Successfully loaded the face landmark model!
INFO 2024-11-29 03:51:59 _internal.py: 97]  * Restarting with watchdog (windowsapi)
DEBUG 2024-11-29 03:52:05 cmd.py: 1253] Popen(['git', 'version'], cwd=E:\Aiwi\github upload\Fake_Face_detection, stdin=None, shell=False, universal_newlines=False)
DEBUG 2024-11-29 03:52:05 cmd.py: 1253] Popen(['git', 'version'], cwd=E:\Aiwi\github upload\Fake_Face_detection, stdin=None, shell=False, universal_newlines=False)
DEBUG 2024-11-29 03:52:06 auth.py: 50] Trying paths: ['C:\\Users\\Hp\\.docker\\config.json', 'C:\\Users\\Hp\\.dockercfg']
DEBUG 2024-11-29 03:52:06 auth.py: 54] Found file at path: C:\Users\Hp\.docker\config.json
DEBUG 2024-11-29 03:52:06 auth.py: 242] Found 'credsStore' section
WARNING 2024-11-29 03:52:09 _internal.py: 97]  * Debugger is active!
INFO 2024-11-29 03:52:09 _internal.py: 97]  * Debugger PIN: 770-194-117
INFO 2024-11-29 03:52:10 BaseModelLoader.py: 34] Successfully parsed the model configuration file meta.json!
